<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="./CSS/style.css">
</head>

<body>
  <?php
  readfile("./Basics/Navbar.html");
  ?>
  <div class="container">
    <p>
      Lorem ipsum dolor sit ament connecter, adipisicing elit. Dolore obcaecati qui assumenda commodi fuga voluptates, sapiente nisi vitae dolorem dolor consectetur libero, mollitia autem eos, sint repellat ipsum est. Mollitia.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste molestias aliquid magni aliquam, suscipit ex cumque sapiente. Ullam necessitatibus amet, alias perferendis animi recusandae officia dignissimos, facilis quo pariatur sequi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam reprehenderit animi reiciendis esse exercitationem perferendis quas excepturi blanditiis, ea officiis consequuntur odio officia accusantium inventore? Sit odit commodi dolores ad. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero architecto autem magnam maxime inventore, placeat eius et velit consequuntur reiciendis recusandae dicta aliquam. Voluptatibus quaerat ea atque autem commodi tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, corporis minus repellendus hic placeat dolor explicabo accusantium culpa architecto, quod omnis aliquid, repellat debitis ea? Natus totam ipsam possimus doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius temporibus fugit delectus nostrum magni, necessitatibus commodi quae ullam natus itaque qui in laudantium, corrupti, exercitationem libero similique ipsum repellat amet.

    </p>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type="text/javascript" src="./JS/javascript.js"></script>
</body>

</html>